serviceName: common_service
development: false
database:
  readDb:
    connectionString: root:admin@tcp(readDb:3306)/baseservices?tls=skip-verify&autocommit=true&parseTime=true
    dbType: postgres
    migrationFilePath: migrations
  writeDb:
    connectionString: root:admin@tcp(writeDb:3306)/baseservices?tls=skip-verify&autocommit=true&parseTime=true
    dbType: postgres
    migrationFilePath: migrations
http:
  port: :5000
  development: false
  shutdownTimeout: 15
  resources: ["internal/resources/en.json",	"internal/resources/fr.json",	"internal/resources/vi.json"]
  allowOrigins: [ "https://cw.gogox.co.kr" ]
  rateLimiting:
    rateFormat: "4-H"
grpc:
  port: :5001
  development: false
  maxConnectionIdle: 5
  timeout: 15
  maxConnectionAge: 5
  time: 10
logger:
  level: debug
  devMode: false
  encoder: json
tracing:
  enable: true
  serviceName: user_service
  hostPort: "jaeger:6831"
  logSpans: false
kafka:
  config:
    brokers: ["kafka1:9092"]
    groupID: user_service_consumer
    initTopics: false
    numWorker: 20
  topics:
    userUpdate:
      topicName: user_update
      numPartitions: 10
      replicationFactor: 1
    userUpdated:
      topicName: user_updated
      numPartitions: 10
      replicationFactor: 1
redis:
  addrs: ["redis:6379"]
  password: ""
  db: 0
  poolSize: 300
heathcheck:
  interval: 10
  port: :6001
  goroutineThreshold: 50
metrics:
  prometheusPath: /metrics
  prometheusPort: :8001
vault:
  address: "https://vault-v2.gogo.tech/"
  path: "gogotech/data/gogovan-korea/ggx-kr-user-service/prod"
  role: "default"
  mountPoint: "gogotech"
s3:
  bucket: "gogox-dev-cw-cms"
  region: "ap-northeast-2"
