version: '3.8'

services:
  readDb:
    image: postgres:latest
    container_name: readDb
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: payment
    ports:
      - 5432:5432
    volumes:
      - ./db/readDb:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    restart: always
    container_name: user_service_redis
    ports:
      - "6379:6379"
