// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.11
// source: common.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated payment
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CommonServiceClient is the client API for CommonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommonServiceClient interface {
	PresignedUrl(ctx context.Context, in *GetPresignedUrlRequest, opts ...grpc.CallOption) (*GetPresignedUrlResponse, error)
	GetConfigurationByKey(ctx context.Context, in *GetConfigurationByKeyRequest, opts ...grpc.CallOption) (*GetConfigurationByKeyResponse, error)
	GetRegionById(ctx context.Context, in *GetRegionByIdRequest, opts ...grpc.CallOption) (*GetRegionByIdResponse, error)
}

type commonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommonServiceClient(cc grpc.ClientConnInterface) CommonServiceClient {
	return &commonServiceClient{cc}
}

func (c *commonServiceClient) PresignedUrl(ctx context.Context, in *GetPresignedUrlRequest, opts ...grpc.CallOption) (*GetPresignedUrlResponse, error) {
	out := new(GetPresignedUrlResponse)
	err := c.cc.Invoke(ctx, "/common.CommonService/PresignedUrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commonServiceClient) GetConfigurationByKey(ctx context.Context, in *GetConfigurationByKeyRequest, opts ...grpc.CallOption) (*GetConfigurationByKeyResponse, error) {
	out := new(GetConfigurationByKeyResponse)
	err := c.cc.Invoke(ctx, "/common.CommonService/GetConfigurationByKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commonServiceClient) GetRegionById(ctx context.Context, in *GetRegionByIdRequest, opts ...grpc.CallOption) (*GetRegionByIdResponse, error) {
	out := new(GetRegionByIdResponse)
	err := c.cc.Invoke(ctx, "/common.CommonService/GetRegionById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommonServiceServer is the server API for CommonService service.
// All implementations should embed UnimplementedCommonServiceServer
// for forward compatibility
type CommonServiceServer interface {
	PresignedUrl(context.Context, *GetPresignedUrlRequest) (*GetPresignedUrlResponse, error)
	GetConfigurationByKey(context.Context, *GetConfigurationByKeyRequest) (*GetConfigurationByKeyResponse, error)
	GetRegionById(context.Context, *GetRegionByIdRequest) (*GetRegionByIdResponse, error)
}

// UnimplementedCommonServiceServer should be embedded to have forward compatible implementations.
type UnimplementedCommonServiceServer struct {
}

func (UnimplementedCommonServiceServer) PresignedUrl(context.Context, *GetPresignedUrlRequest) (*GetPresignedUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PresignedUrl not implemented")
}
func (UnimplementedCommonServiceServer) GetConfigurationByKey(context.Context, *GetConfigurationByKeyRequest) (*GetConfigurationByKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfigurationByKey not implemented")
}
func (UnimplementedCommonServiceServer) GetRegionById(context.Context, *GetRegionByIdRequest) (*GetRegionByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRegionById not implemented")
}

// UnsafeCommonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommonServiceServer will
// result in compilation errors.
type UnsafeCommonServiceServer interface {
	mustEmbedUnimplementedCommonServiceServer()
}

func RegisterCommonServiceServer(s grpc.ServiceRegistrar, srv CommonServiceServer) {
	s.RegisterService(&CommonService_ServiceDesc, srv)
}

func _CommonService_PresignedUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPresignedUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommonServiceServer).PresignedUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.CommonService/PresignedUrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommonServiceServer).PresignedUrl(ctx, req.(*GetPresignedUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommonService_GetConfigurationByKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigurationByKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommonServiceServer).GetConfigurationByKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.CommonService/GetConfigurationByKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommonServiceServer).GetConfigurationByKey(ctx, req.(*GetConfigurationByKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommonService_GetRegionById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRegionByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommonServiceServer).GetRegionById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.CommonService/GetRegionById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommonServiceServer).GetRegionById(ctx, req.(*GetRegionByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CommonService_ServiceDesc is the grpc.ServiceDesc for CommonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "common.CommonService",
	HandlerType: (*CommonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PresignedUrl",
			Handler:    _CommonService_PresignedUrl_Handler,
		},
		{
			MethodName: "GetConfigurationByKey",
			Handler:    _CommonService_GetConfigurationByKey_Handler,
		},
		{
			MethodName: "GetRegionById",
			Handler:    _CommonService_GetRegionById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common.proto",
}
