serviceName: common_service
development: false
database:
  readDb:
    connectionString: VAULT_DATA
    dbType: postgres
    migrationFilePath: migrations
  writeDb:
    connectionString: VAULT_DATA
    dbType: postgres
    migrationFilePath: migrations
http:
  port: :5000
  development: false
  shutdownTimeout: 15
  resources: ["internal/resources/en.json",	"internal/resources/fr.json",	"internal/resources/vi.json"]
  allowOrigins: [ "https://dev-cw.gogox.co.kr" ]
  rateLimiting:
    rateFormat: "100-S"
grpc:
  port: :5001
  development: false
  maxConnectionIdle: 5
  timeout: 15
  maxConnectionAge: 5
  time: 10
logger:
  level: info
  devMode: false
  encoder: json
tracing:
  enable: true
  serviceName: user_service
  hostPort: "localhost:6831"
  logSpans: false
kafka:
  config:
    brokers: ["localhost:9092"]
    groupID: user_service_consumer
    initTopics: false
    numWorker: 20
  topics:
    userUpdate:
      topicName: user_update
      numPartitions: 10
      replicationFactor: 1
    userUpdated:
      topicName: user_updated
      numPartitions: 10
      replicationFactor: 1
redis:
  addrs: ["localhost:6379"]
  password: ""
  db: 0
  poolSize: 300
heathcheck:
  interval: 10
  port: :6001
  goroutineThreshold: 50
metrics:
  prometheusPath: /metrics
  prometheusPort: :8001
s3:
  bucket: "gogox-dev-cw-cms"
  region: "ap-northeast-2"
  accessKey: vault_data
  accessKeySecret: vault_data
vault:
  address: "https://vault-v2.gogo.tech/"
  path: "gogotech/data/gogovan-korea/ggx-kr-common-service/dev"
  role: "default"
  mountPoint: "gogotech"
  token: "s.UwIe1KPMcdyWRLPNcfMy8xXx"

